// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixmul_matrixmul,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.022000,HLS_SYN_LAT=106,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=114,HLS_SYN_LUT=241,HLS_VERSION=2024_1}" *)

module matrixmul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        b_address0,
        b_ce0,
        b_q0,
        res_address0,
        res_ce0,
        res_we0,
        res_d0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] a_address0;
output   a_ce0;
input  [7:0] a_q0;
output  [3:0] b_address0;
output   b_ce0;
input  [7:0] b_q0;
output  [3:0] res_address0;
output   res_ce0;
output   res_we0;
output  [15:0] res_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] add_ln19_fu_107_p2;
reg   [1:0] add_ln19_reg_180;
wire    ap_CS_fsm_state2;
wire   [3:0] sub_ln26_fu_125_p2;
reg   [3:0] sub_ln26_reg_185;
wire   [1:0] add_ln21_fu_137_p2;
reg   [1:0] add_ln21_reg_194;
wire    ap_CS_fsm_state3;
wire   [3:0] add_ln28_fu_147_p2;
reg   [3:0] add_ln28_reg_199;
wire    grp_matrixmul_Pipeline_Product_fu_81_ap_start;
wire    grp_matrixmul_Pipeline_Product_fu_81_ap_done;
wire    grp_matrixmul_Pipeline_Product_fu_81_ap_idle;
wire    grp_matrixmul_Pipeline_Product_fu_81_ap_ready;
wire   [3:0] grp_matrixmul_Pipeline_Product_fu_81_a_address0;
wire    grp_matrixmul_Pipeline_Product_fu_81_a_ce0;
wire   [3:0] grp_matrixmul_Pipeline_Product_fu_81_b_address0;
wire    grp_matrixmul_Pipeline_Product_fu_81_b_ce0;
wire   [15:0] grp_matrixmul_Pipeline_Product_fu_81_tmp_out;
wire    grp_matrixmul_Pipeline_Product_fu_81_tmp_out_ap_vld;
reg   [1:0] j_reg_69;
wire   [0:0] icmp_ln19_fu_101_p2;
wire    ap_CS_fsm_state5;
reg    grp_matrixmul_Pipeline_Product_fu_81_ap_start_reg;
wire   [0:0] icmp_ln21_fu_131_p2;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln28_1_fu_156_p1;
reg   [1:0] i_fu_48;
reg    res_we0_local;
reg    res_ce0_local;
wire   [3:0] p_shl_fu_117_p3;
wire   [3:0] zext_ln26_fu_113_p1;
wire   [3:0] zext_ln28_fu_143_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_matrixmul_Pipeline_Product_fu_81_ap_start_reg = 1'b0;
#0 i_fu_48 = 2'd0;
end

matrixmul_matrixmul_Pipeline_Product grp_matrixmul_Pipeline_Product_fu_81(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matrixmul_Pipeline_Product_fu_81_ap_start),
    .ap_done(grp_matrixmul_Pipeline_Product_fu_81_ap_done),
    .ap_idle(grp_matrixmul_Pipeline_Product_fu_81_ap_idle),
    .ap_ready(grp_matrixmul_Pipeline_Product_fu_81_ap_ready),
    .mul_ln26_1(sub_ln26_reg_185),
    .a_address0(grp_matrixmul_Pipeline_Product_fu_81_a_address0),
    .a_ce0(grp_matrixmul_Pipeline_Product_fu_81_a_ce0),
    .a_q0(a_q0),
    .zext_ln21(j_reg_69),
    .b_address0(grp_matrixmul_Pipeline_Product_fu_81_b_address0),
    .b_ce0(grp_matrixmul_Pipeline_Product_fu_81_b_ce0),
    .b_q0(b_q0),
    .tmp_out(grp_matrixmul_Pipeline_Product_fu_81_tmp_out),
    .tmp_out_ap_vld(grp_matrixmul_Pipeline_Product_fu_81_tmp_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matrixmul_Pipeline_Product_fu_81_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln21_fu_131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_matrixmul_Pipeline_Product_fu_81_ap_start_reg <= 1'b1;
        end else if ((grp_matrixmul_Pipeline_Product_fu_81_ap_ready == 1'b1)) begin
            grp_matrixmul_Pipeline_Product_fu_81_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_48 <= 2'd0;
    end else if (((icmp_ln21_fu_131_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_fu_48 <= add_ln19_reg_180;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_reg_69 <= add_ln21_reg_194;
    end else if (((icmp_ln19_fu_101_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_69 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln19_reg_180 <= add_ln19_fu_107_p2;
        sub_ln26_reg_185 <= sub_ln26_fu_125_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln21_reg_194 <= add_ln21_fu_137_p2;
        add_ln28_reg_199 <= add_ln28_fu_147_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_matrixmul_Pipeline_Product_fu_81_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln19_fu_101_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln19_fu_101_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_ce0_local = 1'b1;
    end else begin
        res_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_we0_local = 1'b1;
    end else begin
        res_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln19_fu_101_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln21_fu_131_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_matrixmul_Pipeline_Product_fu_81_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = grp_matrixmul_Pipeline_Product_fu_81_a_address0;

assign a_ce0 = grp_matrixmul_Pipeline_Product_fu_81_a_ce0;

assign add_ln19_fu_107_p2 = (i_fu_48 + 2'd1);

assign add_ln21_fu_137_p2 = (j_reg_69 + 2'd1);

assign add_ln28_fu_147_p2 = (sub_ln26_reg_185 + zext_ln28_fu_143_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign b_address0 = grp_matrixmul_Pipeline_Product_fu_81_b_address0;

assign b_ce0 = grp_matrixmul_Pipeline_Product_fu_81_b_ce0;

assign grp_matrixmul_Pipeline_Product_fu_81_ap_start = grp_matrixmul_Pipeline_Product_fu_81_ap_start_reg;

assign icmp_ln19_fu_101_p2 = ((i_fu_48 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_131_p2 = ((j_reg_69 == 2'd3) ? 1'b1 : 1'b0);

assign p_shl_fu_117_p3 = {{i_fu_48}, {2'd0}};

assign res_address0 = zext_ln28_1_fu_156_p1;

assign res_ce0 = res_ce0_local;

assign res_d0 = grp_matrixmul_Pipeline_Product_fu_81_tmp_out;

assign res_we0 = res_we0_local;

assign sub_ln26_fu_125_p2 = (p_shl_fu_117_p3 - zext_ln26_fu_113_p1);

assign zext_ln26_fu_113_p1 = i_fu_48;

assign zext_ln28_1_fu_156_p1 = add_ln28_reg_199;

assign zext_ln28_fu_143_p1 = j_reg_69;

endmodule //matrixmul
